// <auto-generated>
//     Generated by native/tools/idlgen from native/kernel.api.json.
//     DO NOT EDIT. Change the IDL and re-run `./build.ps1 -Generate`.
//     CI fails if these files are out of step with the IDL.
// </auto-generated>

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace OpenMCAD.Kernel.Occt.Interop;

/// <summary>
/// Source-generated P/Invoke declarations for the geometry shim.
/// </summary>
/// <remarks>
/// <para>
/// Generated from <c>native/kernel.api.json</c>. Every method is a direct one-to-one
/// mapping of a C entry point and does no interpretation: status codes come back as
/// integers, handles as <see cref="ulong"/>, buffers as spans. Turning those into
/// <c>OperationResult</c> is the job of the hand-written layer above.
/// </para>
/// <para>
/// <see cref="LibraryImportAttribute"/> rather than <c>DllImport</c>: it is
/// source-generated, so the marshalling code is visible and steppable, it is
/// NativeAOT-compatible, and it is allocation-free for the blittable signatures that
/// make up nearly all of this surface (ADR-0003).
/// </para>
/// </remarks>
internal static partial class OcctBindings
{
    /// <summary>The native library name, resolved by the default probing rules.</summary>
    internal const string Library = "openmcad_occt";

    // --- lifetime --------------------------------------------------------------

    /// <summary>Initialises the shim. Must be called once per process before any other entry point. Installs the OCCT signal handler so a floating-point fault inside the kernel becomes a catchable failure rather than a process death.</summary>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_initialize")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Initialize();

    /// <summary>Releases process-wide shim resources. Optional; provided so leak detection has a clean baseline.</summary>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_shutdown")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Shutdown();

    /// <summary>Returns the shim and kernel version as UTF-8.</summary>
    /// <param name="text">The version string.</param>
    /// <param name="textCapacity">The capacity of <paramref name="text"/>, or zero to query the required size.</param>
    /// <param name="textRequired">Receives the number of elements <paramref name="text"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_version")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Version(
        Span<byte> text, int textCapacity, out int textRequired);

    /// <summary>Drops one reference to a shape. The shape and all its sub-entities become invalid when the last reference goes.</summary>
    /// <param name="shape">The shape to release.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_shape_release")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int ShapeRelease(
        ulong shape);

    /// <summary>Takes an additional reference to a shape.</summary>
    /// <param name="shape">The shape to reference.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_shape_add_ref")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int ShapeAddRef(
        ulong shape);

    /// <summary>Releases a history map.</summary>
    /// <param name="history">The history map to release.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_release")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryRelease(
        ulong history);

    /// <summary>Releases a tessellation.</summary>
    /// <param name="mesh">The mesh to release.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_release")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshRelease(
        ulong mesh);

    // --- diagnostics -----------------------------------------------------------

    /// <summary>Returns a description of the most recent failure on the calling thread.</summary>
    /// <param name="text">The description.</param>
    /// <param name="textCapacity">The capacity of <paramref name="text"/>, or zero to query the required size.</param>
    /// <param name="textRequired">Receives the number of elements <paramref name="text"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_last_error")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int LastError(
        Span<byte> text, int textCapacity, out int textRequired);

    /// <summary>Returns how many diagnostics the last operation produced.</summary>
    /// <param name="count">The number of diagnostics.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_diagnostic_count")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int DiagnosticCount(
        out int count);

    /// <summary>Returns one diagnostic severity.</summary>
    /// <param name="index">The diagnostic index.</param>
    /// <param name="severity">0 information, 1 warning, 2 error.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_diagnostic_severity")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int DiagnosticSeverity(
        int index,
        out int severity);

    /// <summary>Returns one diagnostic stable code.</summary>
    /// <param name="index">The diagnostic index.</param>
    /// <param name="code">The code, such as OMK2003.</param>
    /// <param name="codeCapacity">The capacity of <paramref name="code"/>, or zero to query the required size.</param>
    /// <param name="codeRequired">Receives the number of elements <paramref name="code"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_diagnostic_code")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int DiagnosticCode(
        int index,
        Span<byte> code, int codeCapacity, out int codeRequired);

    /// <summary>Returns one diagnostic user-facing message.</summary>
    /// <param name="index">The diagnostic index.</param>
    /// <param name="message">The message.</param>
    /// <param name="messageCapacity">The capacity of <paramref name="message"/>, or zero to query the required size.</param>
    /// <param name="messageRequired">Receives the number of elements <paramref name="message"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_diagnostic_message")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int DiagnosticMessage(
        int index,
        Span<byte> message, int messageCapacity, out int messageRequired);

    /// <summary>Returns the entities one diagnostic refers to.</summary>
    /// <param name="index">The diagnostic index.</param>
    /// <param name="entities">The entity tags.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_diagnostic_entities")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int DiagnosticEntities(
        int index,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);

    /// <summary>Discards the diagnostics from the last operation.</summary>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_diagnostics_clear")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int DiagnosticsClear();

    // --- primitives ------------------------------------------------------------

    /// <summary>Creates a box with its minimum corner at the placement origin.</summary>
    /// <param name="sizeX">Extent along local X, in metres.</param>
    /// <param name="sizeY">Extent along local Y, in metres.</param>
    /// <param name="sizeZ">Extent along local Z, in metres.</param>
    /// <param name="placement">Where the local frame sits.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_create_box")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CreateBox(
        double sizeX,
        double sizeY,
        double sizeZ,
        ReadOnlySpan<double> placement,
        out ulong result,
        out ulong history);

    /// <summary>Creates a cylinder about the local Z axis.</summary>
    /// <param name="radius">Radius in metres.</param>
    /// <param name="height">Height in metres.</param>
    /// <param name="placement">Where the local frame sits.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_create_cylinder")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CreateCylinder(
        double radius,
        double height,
        ReadOnlySpan<double> placement,
        out ulong result,
        out ulong history);

    /// <summary>Creates a sphere centred on the placement origin.</summary>
    /// <param name="radius">Radius in metres.</param>
    /// <param name="placement">Where the local frame sits.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_create_sphere")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CreateSphere(
        double radius,
        ReadOnlySpan<double> placement,
        out ulong result,
        out ulong history);

    /// <summary>Creates a cone or truncated cone about the local Z axis.</summary>
    /// <param name="bottomRadius">Radius at the base, in metres.</param>
    /// <param name="topRadius">Radius at the top, in metres.</param>
    /// <param name="height">Height in metres.</param>
    /// <param name="placement">Where the local frame sits.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_create_cone")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CreateCone(
        double bottomRadius,
        double topRadius,
        double height,
        ReadOnlySpan<double> placement,
        out ulong result,
        out ulong history);

    /// <summary>Creates a torus about the local Z axis.</summary>
    /// <param name="majorRadius">Distance from the axis to the tube centre.</param>
    /// <param name="minorRadius">Tube radius.</param>
    /// <param name="placement">Where the local frame sits.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_create_torus")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CreateTorus(
        double majorRadius,
        double minorRadius,
        ReadOnlySpan<double> placement,
        out ulong result,
        out ulong history);

    /// <summary>Creates a closed planar profile from an outline.</summary>
    /// <param name="points">The outline in the frame XY plane, without a repeated closing point.</param>
    /// <param name="pointsCount">The number of elements in <paramref name="points"/>.</param>
    /// <param name="frame">Maps the profile plane into the world.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_create_polygon_profile")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CreatePolygonProfile(
        ReadOnlySpan<double> points, int pointsCount,
        ReadOnlySpan<double> frame,
        out ulong result,
        out ulong history);

    // --- construction ----------------------------------------------------------

    /// <summary>Sweeps a profile along a straight path.</summary>
    /// <param name="profile">The profile to sweep.</param>
    /// <param name="direction">The sweep direction, unit length.</param>
    /// <param name="distance">How far to sweep, in metres.</param>
    /// <param name="capped">Whether to cap the ends, producing a solid.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_extrude")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Extrude(
        ulong profile,
        ReadOnlySpan<double> direction,
        double distance,
        int capped,
        out ulong result,
        out ulong history);

    /// <summary>Sweeps a profile about an axis.</summary>
    /// <param name="profile">The profile to sweep.</param>
    /// <param name="axisPoint">A point on the axis.</param>
    /// <param name="axisDirection">The axis direction, unit length.</param>
    /// <param name="angle">How far to revolve, in radians.</param>
    /// <param name="capped">Whether to cap the ends of a partial revolution.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_revolve")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Revolve(
        ulong profile,
        ReadOnlySpan<double> axisPoint,
        ReadOnlySpan<double> axisDirection,
        double angle,
        int capped,
        out ulong result,
        out ulong history);

    // --- modification ----------------------------------------------------------

    /// <summary>Combines bodies.</summary>
    /// <param name="operation">0 union, 1 subtract, 2 intersect.</param>
    /// <param name="target">The body being modified.</param>
    /// <param name="tools">The bodies being combined with it.</param>
    /// <param name="toolsCount">The number of elements in <paramref name="tools"/>.</param>
    /// <param name="tolerance">Model tolerance in metres.</param>
    /// <param name="fuzzyTolerance">Relaxed tolerance for rung 3, or zero for none.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <param name="rung">Which rung of the retry ladder produced the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_boolean")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Boolean(
        int operation,
        ulong target,
        ReadOnlySpan<ulong> tools, int toolsCount,
        double tolerance,
        double fuzzyTolerance,
        out ulong result,
        out ulong history,
        out int rung);

    /// <summary>Rounds edges.</summary>
    /// <param name="body">The body to modify.</param>
    /// <param name="edges">The edges to round.</param>
    /// <param name="edgesCount">The number of elements in <paramref name="edges"/>.</param>
    /// <param name="radii">One radius per edge, in metres.</param>
    /// <param name="radiiCount">The number of elements in <paramref name="radii"/>.</param>
    /// <param name="tolerance">Model tolerance in metres.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <param name="rung">Which rung of the retry ladder produced the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_fillet")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Fillet(
        ulong body,
        ReadOnlySpan<ulong> edges, int edgesCount,
        ReadOnlySpan<double> radii, int radiiCount,
        double tolerance,
        out ulong result,
        out ulong history,
        out int rung);

    /// <summary>Bevels edges.</summary>
    /// <param name="body">The body to modify.</param>
    /// <param name="edges">The edges to bevel.</param>
    /// <param name="edgesCount">The number of elements in <paramref name="edges"/>.</param>
    /// <param name="distances">One setback distance per edge, in metres.</param>
    /// <param name="distancesCount">The number of elements in <paramref name="distances"/>.</param>
    /// <param name="tolerance">Model tolerance in metres.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <param name="rung">Which rung of the retry ladder produced the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_chamfer")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Chamfer(
        ulong body,
        ReadOnlySpan<ulong> edges, int edgesCount,
        ReadOnlySpan<double> distances, int distancesCount,
        double tolerance,
        out ulong result,
        out ulong history,
        out int rung);

    // --- queries ---------------------------------------------------------------

    /// <summary>Computes volume, area, centroid, and inertia.</summary>
    /// <param name="shape">The shape to measure.</param>
    /// <param name="density">Density in kilograms per cubic metre.</param>
    /// <param name="values">Eleven doubles: volume, area, centroid xyz, then Ixx Iyy Izz Ixy Ixz Iyz. Always 11 elements.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <param name="accuracy">0 exact, 1 approximate.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mass_properties")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MassProperties(
        ulong shape,
        double density,
        Span<double> values, int valuesCapacity, out int valuesRequired,
        out int accuracy);

    /// <summary>Computes the axis-aligned bound.</summary>
    /// <param name="shape">The shape to bound.</param>
    /// <param name="values">Six doubles: min xyz then max xyz. Always 6 elements.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_bounding_box")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int BoundingBox(
        ulong shape,
        Span<double> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Counts topological entities.</summary>
    /// <param name="shape">The shape to count.</param>
    /// <param name="values">Six counts: solids, shells, faces, wires, edges, vertices. Always 6 elements.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_topology_counts")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int TopologyCounts(
        ulong shape,
        Span<int> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Lists entities of one kind in canonical order.</summary>
    /// <param name="shape">The shape to enumerate.</param>
    /// <param name="kind">The SubEntityKind to list.</param>
    /// <param name="entities">The entity tags, in canonical order.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_enumerate")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Enumerate(
        ulong shape,
        int kind,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);

    /// <summary>Returns what kind of entity a tag refers to.</summary>
    /// <param name="shape">The owning shape.</param>
    /// <param name="entity">The entity tag.</param>
    /// <param name="kind">The SubEntityKind.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_entity_kind")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int EntityKind(
        ulong shape,
        ulong entity,
        out int kind);

    /// <summary>Checks a shape for structural validity.</summary>
    /// <param name="shape">The shape to check.</param>
    /// <param name="isValid">Non-zero when the shape is sound.</param>
    /// <param name="isClosed">Non-zero when its shells are closed.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_check_validity")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int CheckValidity(
        ulong shape,
        out int isValid,
        out int isClosed);

    // --- tessellation ----------------------------------------------------------

    /// <summary>Triangulates a shape, returning a mesh handle.</summary>
    /// <param name="shape">The shape to tessellate.</param>
    /// <param name="chordalDeviation">Maximum deviation from the true surface, in metres.</param>
    /// <param name="angularDeviation">Maximum angle between adjacent facet normals, in radians.</param>
    /// <param name="relative">Whether the chordal deviation is relative to shape size.</param>
    /// <param name="computeNormals">Whether to compute per-vertex normals.</param>
    /// <param name="mesh">The resulting mesh.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_triangulate")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int Triangulate(
        ulong shape,
        double chordalDeviation,
        double angularDeviation,
        int relative,
        int computeNormals,
        out ulong mesh);

    /// <summary>Returns a mesh size, so buffers can be allocated once.</summary>
    /// <param name="mesh">The mesh.</param>
    /// <param name="values">Three counts: vertices, triangles, faces. Always 3 elements.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_counts")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshCounts(
        ulong mesh,
        Span<int> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Returns vertex positions as XYZ triples in metres.</summary>
    /// <param name="mesh">The mesh.</param>
    /// <param name="values">Three doubles per vertex.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_positions")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshPositions(
        ulong mesh,
        Span<double> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Returns per-vertex normals as XYZ triples.</summary>
    /// <param name="mesh">The mesh.</param>
    /// <param name="values">Three doubles per vertex, empty if not computed.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_normals")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshNormals(
        ulong mesh,
        Span<double> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Returns triangle vertex indices, three per triangle.</summary>
    /// <param name="mesh">The mesh.</param>
    /// <param name="values">Three indices per triangle.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_indices")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshIndices(
        ulong mesh,
        Span<int> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Returns the face index each triangle came from.</summary>
    /// <param name="mesh">The mesh.</param>
    /// <param name="values">One index per triangle.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_triangle_faces")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshTriangleFaces(
        ulong mesh,
        Span<int> values, int valuesCapacity, out int valuesRequired);

    /// <summary>Returns the face tags the triangle attribution indexes into.</summary>
    /// <param name="mesh">The mesh.</param>
    /// <param name="values">The face tags, in order.</param>
    /// <param name="valuesCapacity">The capacity of <paramref name="values"/>, or zero to query the required size.</param>
    /// <param name="valuesRequired">Receives the number of elements <paramref name="values"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_mesh_faces")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int MeshFaces(
        ulong mesh,
        Span<ulong> values, int valuesCapacity, out int valuesRequired);

    // --- serialisation ---------------------------------------------------------

    /// <summary>Writes a shape to the kernel native format.</summary>
    /// <param name="shape">The shape to write.</param>
    /// <param name="data">The bytes.</param>
    /// <param name="dataCapacity">The capacity of <paramref name="data"/>, or zero to query the required size.</param>
    /// <param name="dataRequired">Receives the number of elements <paramref name="data"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_write_brep")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int WriteBRep(
        ulong shape,
        Span<byte> data, int dataCapacity, out int dataRequired);

    /// <summary>Reads a shape written by write_brep.</summary>
    /// <param name="data">The bytes to read.</param>
    /// <param name="dataCount">The number of elements in <paramref name="data"/>.</param>
    /// <param name="result">The resulting shape.</param>
    /// <param name="history">The correspondence between the inputs and the result.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_read_brep")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int ReadBRep(
        ReadOnlySpan<byte> data, int dataCount,
        out ulong result,
        out ulong history);

    /// <summary>Writes shapes as a STEP AP242 file.</summary>
    /// <param name="shapes">The shapes to write.</param>
    /// <param name="shapesCount">The number of elements in <paramref name="shapes"/>.</param>
    /// <param name="path">Where to write. The OCCT writer wants a path, not a stream.</param>
    /// <param name="bytesWritten">How many bytes were written.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_write_step", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int WriteStep(
        ReadOnlySpan<ulong> shapes, int shapesCount,
        string path,
        out int bytesWritten);

    // --- history ---------------------------------------------------------------

    /// <summary>Returns the entities an input caused to come into existence.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="input">The input entity.</param>
    /// <param name="entities">The generated entities, sorted.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_generated")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryGenerated(
        ulong history,
        ulong input,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);

    /// <summary>Returns the altered successors of an input.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="input">The input entity.</param>
    /// <param name="entities">The successors, sorted.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_modified")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryModified(
        ulong history,
        ulong input,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);

    /// <summary>Returns whether an input has no successor.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="input">The input entity.</param>
    /// <param name="deleted">Non-zero when the entity was consumed.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_is_deleted")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryIsDeleted(
        ulong history,
        ulong input,
        out int deleted);

    /// <summary>Returns the entities created from nothing.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="entities">The new entities, sorted.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_new_entities")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryNewEntities(
        ulong history,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);

    /// <summary>Returns what an output entity is, in the terms of the operation that made it.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="output">The output entity.</param>
    /// <param name="role">The OperationRole. Zero means unassigned, which is a defect.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_role_of")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryRoleOf(
        ulong history,
        ulong output,
        out int role);

    /// <summary>Returns the input an output came from.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="output">The output entity.</param>
    /// <param name="source">The source entity tag, or zero for entities created from nothing.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_source_of")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistorySourceOf(
        ulong history,
        ulong output,
        out ulong source);

    /// <summary>Returns every output the map describes.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="entities">The outputs, sorted.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_outputs")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryOutputs(
        ulong history,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);

    /// <summary>Returns every input the map describes.</summary>
    /// <param name="history">The history map.</param>
    /// <param name="entities">The inputs, sorted.</param>
    /// <param name="entitiesCapacity">The capacity of <paramref name="entities"/>, or zero to query the required size.</param>
    /// <param name="entitiesRequired">Receives the number of elements <paramref name="entities"/> needs.</param>
    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>
    [LibraryImport(Library, EntryPoint = "openmcad_history_inputs")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int HistoryInputs(
        ulong history,
        Span<ulong> entities, int entitiesCapacity, out int entitiesRequired);
}
