using System.Text;

namespace OpenMCAD.IdlGen;

/// <summary>Shared helpers for the emitters.</summary>
internal static class EmitHelp
{
    internal const string Banner =
        "// <auto-generated>\n"
        + "//     Generated by native/tools/idlgen from native/kernel.api.json.\n"
        + "//     DO NOT EDIT. Change the IDL and re-run `./build.ps1 -Generate`.\n"
        + "//     CI fails if these files are out of step with the IDL.\n"
        + "// </auto-generated>\n";

    internal static void Section(StringBuilder text, string title)
    {
        text.AppendLine();
        text.AppendLine($"/* --- {title} {new string('-', System.Math.Max(4, 74 - title.Length))} */");
        text.AppendLine();
    }

    internal static IEnumerable<IGrouping<string, Operation>> Grouped(ApiDocument document)
        => document.Operations.GroupBy(o => o.Group);

    internal static string CParameterList(Operation operation)
    {
        List<string> parts = [.. operation.Parameters.Select(
            p => TypeTable.For(p.Type).CParameters(p.Name))];

        return parts.Count == 0 ? "void" : string.Join(",\n    ", parts);
    }

    internal static string DocLines(string summary, string indent, string prefix = "///")
    {
        List<string> lines = [];
        foreach (string word in Wrap(summary, 92 - indent.Length))
        {
            lines.Add($"{indent}{prefix} {word}");
        }

        return string.Join("\n", lines);
    }

    internal static IEnumerable<string> Wrap(string text, int width)
    {
        string[] words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        StringBuilder line = new();

        foreach (string word in words)
        {
            if (line.Length > 0 && line.Length + 1 + word.Length > width)
            {
                yield return line.ToString();
                line.Clear();
            }

            if (line.Length > 0)
            {
                line.Append(' ');
            }

            line.Append(word);
        }

        if (line.Length > 0)
        {
            yield return line.ToString();
        }
    }

    internal static string XmlEscape(string value)
        => value.Replace("&", "&amp;", StringComparison.Ordinal)
                .Replace("<", "&lt;", StringComparison.Ordinal)
                .Replace(">", "&gt;", StringComparison.Ordinal);
}

/// <summary>Emits the C declarations.</summary>
internal static class CHeaderEmitter
{
    internal static string Emit(ApiDocument document)
    {
        StringBuilder text = new();
        text.Append(EmitHelp.Banner);
        text.AppendLine();
        text.AppendLine("#ifndef OPENMCAD_OCCT_G_H");
        text.AppendLine("#define OPENMCAD_OCCT_G_H");
        text.AppendLine();
        text.AppendLine("#include <stdint.h>");
        text.AppendLine();
        text.AppendLine("#include \"openmcad_occt.h\"");
        text.AppendLine();
        text.AppendLine("#ifdef __cplusplus");
        text.AppendLine("extern \"C\" {");
        text.AppendLine("#endif");

        foreach (IGrouping<string, Operation> group in EmitHelp.Grouped(document))
        {
            EmitHelp.Section(text, group.Key);

            foreach (Operation operation in group)
            {
                text.AppendLine("/*");
                foreach (string line in EmitHelp.Wrap(operation.Summary, 92))
                {
                    text.AppendLine($" * {line}");
                }

                if (operation.Fragile)
                {
                    text.AppendLine(" *");
                    text.AppendLine(" * Fragile: escalates through the retry ladder (PLAN.md 5.2.4) and reports which");
                    text.AppendLine(" * rung succeeded.");
                }

                foreach (Parameter parameter in operation.Parameters)
                {
                    text.AppendLine(" *");
                    IEnumerable<string> wrapped = EmitHelp.Wrap(parameter.Summary, 76);
                    bool first = true;
                    foreach (string line in wrapped)
                    {
                        text.AppendLine(first ? $" * @param {parameter.Name} {line}" : $" *        {line}");
                        first = false;
                    }

                    if (parameter.Fixed is int size)
                    {
                        text.AppendLine($" *        Always {size} elements; the size query can be skipped.");
                    }
                }

                text.AppendLine(" */");
                text.AppendLine(
                    $"OPENMCAD_API OpenMcadStatus OPENMCAD_CALL {operation.CSymbol(document.Prefix)}(");
                text.AppendLine($"    {EmitHelp.CParameterList(operation)});");
                text.AppendLine();
            }
        }

        text.AppendLine("#ifdef __cplusplus");
        text.AppendLine("} /* extern \"C\" */");
        text.AppendLine("#endif");
        text.AppendLine();
        text.AppendLine("#endif /* OPENMCAD_OCCT_G_H */");
        return text.ToString();
    }
}

/// <summary>Emits the signatures the hand-written implementations must provide.</summary>
internal static class OpsHeaderEmitter
{
    internal static string Emit(ApiDocument document)
    {
        StringBuilder text = new();
        text.Append(EmitHelp.Banner);
        text.AppendLine();
        text.AppendLine("#ifndef OPENMCAD_OPS_G_H");
        text.AppendLine("#define OPENMCAD_OPS_G_H");
        text.AppendLine();
        text.AppendLine("#include <span>");
        text.AppendLine("#include <stdint.h>");
        text.AppendLine();
        text.AppendLine("#include \"openmcad_types.h\"");
        text.AppendLine();
        text.AppendLine("/*");
        text.AppendLine(" * The operation bodies, which are hand-written -- everything around them is generated.");
        text.AppendLine(" *");
        text.AppendLine(" * By the time one of these is called the dispatch layer has already: rejected null");
        text.AppendLine(" * output pointers, resolved handles against the handle table, wrapped raw pointers in");
        text.AppendLine(" * spans, and installed the exception firewall. An implementation may therefore throw");
        text.AppendLine(" * freely -- Standard_Failure included -- and work in C++ types rather than in ABI types.");
        text.AppendLine(" *");
        text.AppendLine(" * None of these signatures mentions OCCT. The generator does not know what kernel is");
        text.AppendLine(" * underneath, which is what keeps ADR-0002 swap path honest.");
        text.AppendLine(" */");
        text.AppendLine();
        text.AppendLine("namespace openmcad::ops {");

        foreach (IGrouping<string, Operation> group in EmitHelp.Grouped(document))
        {
            EmitHelp.Section(text, group.Key);

            foreach (Operation operation in group)
            {
                List<string> parts = [.. operation.Parameters.Select(
                    p => TypeTable.For(p.Type).OpsParameter(p.Name))];

                string parameters = parts.Count == 0 ? string.Empty : string.Join(",\n    ", parts);
                text.AppendLine($"void {operation.Name}(");
                text.AppendLine(parts.Count == 0 ? "    );" : $"    {parameters});");
                text.AppendLine();
            }
        }

        text.AppendLine("} // namespace openmcad::ops");
        text.AppendLine();
        text.AppendLine("#endif /* OPENMCAD_OPS_G_H */");
        return text.ToString();
    }
}

/// <summary>Emits the exported entry points: unpacking, firewall, status return.</summary>
internal static class DispatchEmitter
{
    internal static string Emit(ApiDocument document)
    {
        StringBuilder text = new();
        text.Append(EmitHelp.Banner);
        text.AppendLine();
        text.AppendLine("#include \"openmcad_occt.g.h\"");
        text.AppendLine("#include \"openmcad_ops.g.h\"");
        text.AppendLine("#include \"openmcad_types.h\"");
        text.AppendLine();
        text.AppendLine("/*");
        text.AppendLine(" * One exported function per operation. Each does exactly four things, in this order:");
        text.AppendLine(" *");
        text.AppendLine(" *   1. Reject null output pointers. A caller that passes one has a bug, and writing");
        text.AppendLine(" *      through it would corrupt their memory rather than report their mistake.");
        text.AppendLine(" *   2. Wrap raw pointers and tags in the C++ vocabulary the implementation expects.");
        text.AppendLine(" *   3. Call the implementation inside the exception firewall.");
        text.AppendLine(" *   4. Return a status. Nothing propagates across the boundary -- a C++ exception");
        text.AppendLine(" *      crossing a C ABI is undefined behaviour, so every entry point catches all.");
        text.AppendLine(" */");

        foreach (IGrouping<string, Operation> group in EmitHelp.Grouped(document))
        {
            EmitHelp.Section(text, group.Key);

            foreach (Operation operation in group)
            {
                text.AppendLine(
                    $"OPENMCAD_API OpenMcadStatus OPENMCAD_CALL {operation.CSymbol(document.Prefix)}(");
                text.AppendLine($"    {EmitHelp.CParameterList(operation)})");
                text.AppendLine("{");

                List<Parameter> checks =
                [
                    .. operation.Parameters.Where(p => TypeTable.For(p.Type).NeedsNullCheck),
                ];

                foreach (Parameter parameter in checks)
                {
                    text.AppendLine($"    if ({parameter.Name} == nullptr)");
                    text.AppendLine("    {");
                    text.AppendLine(
                        $"        return openmcad::fail_null(\"{operation.CSymbol(document.Prefix)}\", "
                        + $"\"{parameter.Name}\");");
                    text.AppendLine("    }");
                    text.AppendLine();
                }

                List<string> arguments = [.. operation.Parameters.Select(
                    p => TypeTable.For(p.Type).OpsArgument(p.Name))];

                text.AppendLine($"    OPENMCAD_GUARD(\"{operation.CSymbol(document.Prefix)}\",");
                text.AppendLine("    {");
                text.AppendLine(arguments.Count == 0
                    ? $"        openmcad::ops::{operation.Name}();"
                    : $"        openmcad::ops::{operation.Name}(\n            "
                        + string.Join(",\n            ", arguments) + ");");
                // Out-buffer parameters use the two-call protocol, and until now the generated
                // dispatch returned OPENMCAD_OK regardless -- so a caller passing a buffer one
                // element short got a success status with nothing written, and read whatever was
                // already in its array. OPENMCAD_ERROR_BUFFER_TOO_SMALL was declared and
                // documented but never actually returned by anything.
                List<string> outBuffers = [.. operation.Parameters
                    .Where(p => TypeTable.For(p.Type).IsOutBuffer)
                    .Select(p => p.Name)];

                foreach (string buffer in outBuffers)
                {
                    text.AppendLine(
                        $"        if (!openmcad::buffer_satisfied({buffer}, {buffer}_capacity, "
                        + $"{buffer}_required))");
                    text.AppendLine("        {");
                    text.AppendLine(
                        $"            openmcad::record_error(\"{operation.CSymbol(document.Prefix)}\",");
                    text.AppendLine(
                        "                \"The buffer is too small. Call again with the "
                        + "reported size.\");");
                    text.AppendLine("            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;");
                    text.AppendLine("        }");
                    text.AppendLine();
                }

                text.AppendLine("        return OPENMCAD_OK;");
                text.AppendLine("    })");
                text.AppendLine("}");
                text.AppendLine();
            }
        }

        return text.ToString();
    }
}

/// <summary>Emits not-implemented fallbacks, so the shim links before any geometry exists.</summary>
internal static class StubEmitter
{
    internal static string Emit(ApiDocument document)
    {
        StringBuilder text = new();
        text.Append(EmitHelp.Banner);
        text.AppendLine();
        text.AppendLine("#include \"openmcad_ops.g.h\"");
        text.AppendLine("#include \"openmcad_types.h\"");
        text.AppendLine();
        text.AppendLine("/*");
        text.AppendLine(" * Fallback bodies, compiled only when OPENMCAD_WITH_OCCT is off.");
        text.AppendLine(" *");
        text.AppendLine(" * With these the shim links and exports its whole ABI before a single geometric");
        text.AppendLine(" * operation exists. That is worth more than it sounds: the boundary, the handle table,");
        text.AppendLine(" * the firewall, the two-call protocol and the C# bindings can all be exercised against a");
        text.AppendLine(" * real DLL while the kernel work is still ahead, instead of everything arriving at once.");
        text.AppendLine(" *");
        text.AppendLine(" * Each throws not_implemented, which the firewall turns into");
        text.AppendLine(" * OPENMCAD_ERROR_NOT_IMPLEMENTED with the operation named in the diagnostic.");
        text.AppendLine(" */");
        text.AppendLine();
        text.AppendLine("namespace openmcad::ops {");
        text.AppendLine();

        foreach (Operation operation in document.Operations)
        {
            if (operation.Handwritten)
            {
                text.AppendLine($"/* {operation.Name}: hand-written in every build; no stub. */");
                text.AppendLine();
                continue;
            }

            List<string> parts = [.. operation.Parameters.Select(
                p => TypeTable.For(p.Type).OpsParameter(p.Name))];

            // Unnamed parameters: a stub uses none of them, and naming them would warn.
            List<string> unnamed = [.. parts.Select(StripName)];

            text.AppendLine($"void {operation.Name}(");
            text.AppendLine(unnamed.Count == 0
                ? "    )"
                : "    " + string.Join(",\n    ", unnamed) + ")");
            text.AppendLine("{");
            text.AppendLine($"    throw openmcad::not_implemented(\"{operation.Name}\");");
            text.AppendLine("}");
            text.AppendLine();
        }

        text.AppendLine("} // namespace openmcad::ops");
        return text.ToString();
    }

    private static string StripName(string declaration)
    {
        int lastSpace = declaration.LastIndexOf(' ');
        return lastSpace < 0 ? declaration : declaration[..lastSpace];
    }
}

/// <summary>Emits the C# P/Invoke declarations.</summary>
internal static class CSharpEmitter
{
    internal static string Emit(ApiDocument document)
    {
        StringBuilder text = new();
        text.Append(EmitHelp.Banner);
        text.AppendLine();
        text.AppendLine("using System.Runtime.CompilerServices;");
        text.AppendLine("using System.Runtime.InteropServices;");
        text.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        text.AppendLine();
        text.AppendLine("namespace OpenMCAD.Kernel.Occt.Interop;");
        text.AppendLine();
        text.AppendLine("/// <summary>");
        text.AppendLine("/// Source-generated P/Invoke declarations for the geometry shim.");
        text.AppendLine("/// </summary>");
        text.AppendLine("/// <remarks>");
        text.AppendLine("/// <para>");
        text.AppendLine("/// Generated from <c>native/kernel.api.json</c>. Every method is a direct one-to-one");
        text.AppendLine("/// mapping of a C entry point and does no interpretation: status codes come back as");
        text.AppendLine("/// integers, handles as <see cref=\"ulong\"/>, buffers as spans. Turning those into");
        text.AppendLine("/// <c>OperationResult</c> is the job of the hand-written layer above.");
        text.AppendLine("/// </para>");
        text.AppendLine("/// <para>");
        text.AppendLine("/// <see cref=\"LibraryImportAttribute\"/> rather than <c>DllImport</c>: it is");
        text.AppendLine("/// source-generated, so the marshalling code is visible and steppable, it is");
        text.AppendLine("/// NativeAOT-compatible, and it is allocation-free for the blittable signatures that");
        text.AppendLine("/// make up nearly all of this surface (ADR-0003).");
        text.AppendLine("/// </para>");
        text.AppendLine("/// </remarks>");
        text.AppendLine("internal static partial class OcctBindings");
        text.AppendLine("{");
        text.AppendLine("    /// <summary>The native library name, resolved by the default probing rules.</summary>");
        text.AppendLine($"    internal const string Library = \"{document.Library}\";");

        foreach (IGrouping<string, Operation> group in EmitHelp.Grouped(document))
        {
            text.AppendLine();
            text.AppendLine($"    // --- {group.Key} {new string('-', System.Math.Max(4, 70 - group.Key.Length))}");

            foreach (Operation operation in group)
            {
                text.AppendLine();
                text.AppendLine($"    /// <summary>{EmitHelp.XmlEscape(operation.Summary)}</summary>");

                foreach (Parameter parameter in operation.Parameters)
                {
                    Marshalling rule = TypeTable.For(parameter.Type);
                    string summary = EmitHelp.XmlEscape(parameter.Summary);

                    if (parameter.Fixed is int size)
                    {
                        summary += $" Always {size} elements.";
                    }

                    foreach (string name in CSharpParameterNames(parameter, rule))
                    {
                        text.AppendLine($"    /// <param name=\"{name}\">{ParameterDoc(name, parameter, summary)}</param>");
                    }
                }

                text.AppendLine("    /// <returns>Zero on success; otherwise an <c>OpenMcadStatus</c> code.</returns>");
                text.AppendLine($"    [LibraryImport(Library, EntryPoint = \"{operation.CSymbol(document.Prefix)}\""
                    + (RequiresStringMarshalling(operation) ? ", StringMarshalling = StringMarshalling.Utf8)]" : ")]"));
                text.AppendLine("    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]");

                List<string> parts = [.. operation.Parameters.Select(
                    p => TypeTable.For(p.Type).CSharpParameters(p.Name is var n ? ToCamel(n) : n))];

                text.AppendLine(parts.Count == 0
                    ? $"    internal static partial int {operation.CSharp}();"
                    : $"    internal static partial int {operation.CSharp}(\n        "
                        + string.Join(",\n        ", parts) + ");");
            }
        }

        text.AppendLine("}");
        return text.ToString();
    }

    private static bool RequiresStringMarshalling(Operation operation)
        => operation.Parameters.Any(p => p.Type == "utf8");

    private static IEnumerable<string> CSharpParameterNames(Parameter parameter, Marshalling rule)
    {
        string declaration = rule.CSharpParameters(ToCamel(parameter.Name));
        foreach (string part in declaration.Split(',', StringSplitOptions.TrimEntries))
        {
            yield return part[(part.LastIndexOf(' ') + 1)..];
        }
    }

    private static string ParameterDoc(string name, Parameter parameter, string summary)
    {
        string camel = ToCamel(parameter.Name);
        if (name == camel)
        {
            return summary;
        }

        if (name.EndsWith("Count", StringComparison.Ordinal))
        {
            return $"The number of elements in <paramref name=\"{camel}\"/>.";
        }

        if (name.EndsWith("Capacity", StringComparison.Ordinal))
        {
            return $"The capacity of <paramref name=\"{camel}\"/>, or zero to query the required size.";
        }

        return $"Receives the number of elements <paramref name=\"{camel}\"/> needs.";
    }

    private static string ToCamel(string snake)
    {
        string[] parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return snake;
        }

        string result = parts[0] + string.Concat(parts.Skip(1)
            .Select(p => char.ToUpperInvariant(p[0]) + p[1..]));

        // "params" and friends would not compile as identifiers.
        return SyntaxKeywords.Contains(result) ? "@" + result : result;
    }

    private static readonly HashSet<string> SyntaxKeywords = new(StringComparer.Ordinal)
    {
        "base", "bool", "byte", "case", "class", "const", "default", "double", "event", "fixed",
        "float", "int", "lock", "long", "namespace", "new", "object", "operator", "out", "params",
        "ref", "return", "short", "string", "struct", "this", "uint", "ulong", "ushort", "void",
    };
}
