<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../OpenMCAD.App/OpenMCAD.App.csproj" />
    <ProjectReference Include="../OpenMCAD.Interaction/OpenMCAD.Interaction.csproj" />
    <ProjectReference Include="../OpenMCAD.Solver/OpenMCAD.Solver.csproj" />
  </ItemGroup>

</Project>
