// <auto-generated>
//     Generated by native/tools/idlgen from native/kernel.api.json.
//     DO NOT EDIT. Change the IDL and re-run `./build.ps1 -Generate`.
//     CI fails if these files are out of step with the IDL.
// </auto-generated>

#include "openmcad_occt.g.h"
#include "openmcad_ops.g.h"
#include "openmcad_types.h"

/*
 * One exported function per operation. Each does exactly four things, in this order:
 *
 *   1. Reject null output pointers. A caller that passes one has a bug, and writing
 *      through it would corrupt their memory rather than report their mistake.
 *   2. Wrap raw pointers and tags in the C++ vocabulary the implementation expects.
 *   3. Call the implementation inside the exception firewall.
 *   4. Return a status. Nothing propagates across the boundary -- a C++ exception
 *      crossing a C ABI is undefined behaviour, so every entry point catches all.
 */

/* --- lifetime ------------------------------------------------------------------ */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_initialize(
    void)
{
    OPENMCAD_GUARD("openmcad_initialize",
    {
        openmcad::ops::initialize();
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_shutdown(
    void)
{
    OPENMCAD_GUARD("openmcad_shutdown",
    {
        openmcad::ops::shutdown();
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_version(
    char* text, int32_t text_capacity, int32_t* text_required)
{
    OPENMCAD_GUARD("openmcad_version",
    {
        openmcad::ops::version(
            openmcad::OutBuffer<char>{text, text_capacity, text_required});
        if (!openmcad::buffer_satisfied(text, text_capacity, text_required))
        {
            openmcad::record_error("openmcad_version",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_shape_release(
    uint64_t shape)
{
    OPENMCAD_GUARD("openmcad_shape_release",
    {
        openmcad::ops::shape_release(
            openmcad::ShapeRef{shape});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_shape_add_ref(
    uint64_t shape)
{
    OPENMCAD_GUARD("openmcad_shape_add_ref",
    {
        openmcad::ops::shape_add_ref(
            openmcad::ShapeRef{shape});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_release(
    uint64_t history)
{
    OPENMCAD_GUARD("openmcad_history_release",
    {
        openmcad::ops::history_release(
            openmcad::HistoryRef{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_release(
    uint64_t mesh)
{
    OPENMCAD_GUARD("openmcad_mesh_release",
    {
        openmcad::ops::mesh_release(
            openmcad::MeshRef{mesh});
        return OPENMCAD_OK;
    })
}


/* --- diagnostics --------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_last_error(
    char* text, int32_t text_capacity, int32_t* text_required)
{
    OPENMCAD_GUARD("openmcad_last_error",
    {
        openmcad::ops::last_error(
            openmcad::OutBuffer<char>{text, text_capacity, text_required});
        if (!openmcad::buffer_satisfied(text, text_capacity, text_required))
        {
            openmcad::record_error("openmcad_last_error",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_count(
    int32_t* count)
{
    if (count == nullptr)
    {
        return openmcad::fail_null("openmcad_diagnostic_count", "count");
    }

    OPENMCAD_GUARD("openmcad_diagnostic_count",
    {
        openmcad::ops::diagnostic_count(
            *count);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_severity(
    int32_t index,
    int32_t* severity)
{
    if (severity == nullptr)
    {
        return openmcad::fail_null("openmcad_diagnostic_severity", "severity");
    }

    OPENMCAD_GUARD("openmcad_diagnostic_severity",
    {
        openmcad::ops::diagnostic_severity(
            index,
            *severity);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_code(
    int32_t index,
    char* code, int32_t code_capacity, int32_t* code_required)
{
    OPENMCAD_GUARD("openmcad_diagnostic_code",
    {
        openmcad::ops::diagnostic_code(
            index,
            openmcad::OutBuffer<char>{code, code_capacity, code_required});
        if (!openmcad::buffer_satisfied(code, code_capacity, code_required))
        {
            openmcad::record_error("openmcad_diagnostic_code",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_message(
    int32_t index,
    char* message, int32_t message_capacity, int32_t* message_required)
{
    OPENMCAD_GUARD("openmcad_diagnostic_message",
    {
        openmcad::ops::diagnostic_message(
            index,
            openmcad::OutBuffer<char>{message, message_capacity, message_required});
        if (!openmcad::buffer_satisfied(message, message_capacity, message_required))
        {
            openmcad::record_error("openmcad_diagnostic_message",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_entities(
    int32_t index,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_diagnostic_entities",
    {
        openmcad::ops::diagnostic_entities(
            index,
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_diagnostic_entities",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostics_clear(
    void)
{
    OPENMCAD_GUARD("openmcad_diagnostics_clear",
    {
        openmcad::ops::diagnostics_clear();
        return OPENMCAD_OK;
    })
}


/* --- primitives ---------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_box(
    double size_x,
    double size_y,
    double size_z,
    const double* placement,
    uint64_t* result,
    uint64_t* history)
{
    if (placement == nullptr)
    {
        return openmcad::fail_null("openmcad_create_box", "placement");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_create_box", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_create_box", "history");
    }

    OPENMCAD_GUARD("openmcad_create_box",
    {
        openmcad::ops::create_box(
            size_x,
            size_y,
            size_z,
            openmcad::Transform::from(placement),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_cylinder(
    double radius,
    double height,
    const double* placement,
    uint64_t* result,
    uint64_t* history)
{
    if (placement == nullptr)
    {
        return openmcad::fail_null("openmcad_create_cylinder", "placement");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_create_cylinder", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_create_cylinder", "history");
    }

    OPENMCAD_GUARD("openmcad_create_cylinder",
    {
        openmcad::ops::create_cylinder(
            radius,
            height,
            openmcad::Transform::from(placement),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_sphere(
    double radius,
    const double* placement,
    uint64_t* result,
    uint64_t* history)
{
    if (placement == nullptr)
    {
        return openmcad::fail_null("openmcad_create_sphere", "placement");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_create_sphere", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_create_sphere", "history");
    }

    OPENMCAD_GUARD("openmcad_create_sphere",
    {
        openmcad::ops::create_sphere(
            radius,
            openmcad::Transform::from(placement),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_cone(
    double bottom_radius,
    double top_radius,
    double height,
    const double* placement,
    uint64_t* result,
    uint64_t* history)
{
    if (placement == nullptr)
    {
        return openmcad::fail_null("openmcad_create_cone", "placement");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_create_cone", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_create_cone", "history");
    }

    OPENMCAD_GUARD("openmcad_create_cone",
    {
        openmcad::ops::create_cone(
            bottom_radius,
            top_radius,
            height,
            openmcad::Transform::from(placement),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_torus(
    double major_radius,
    double minor_radius,
    const double* placement,
    uint64_t* result,
    uint64_t* history)
{
    if (placement == nullptr)
    {
        return openmcad::fail_null("openmcad_create_torus", "placement");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_create_torus", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_create_torus", "history");
    }

    OPENMCAD_GUARD("openmcad_create_torus",
    {
        openmcad::ops::create_torus(
            major_radius,
            minor_radius,
            openmcad::Transform::from(placement),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_polygon_profile(
    const double* points, int32_t points_count,
    const double* frame,
    uint64_t* result,
    uint64_t* history)
{
    if (frame == nullptr)
    {
        return openmcad::fail_null("openmcad_create_polygon_profile", "frame");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_create_polygon_profile", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_create_polygon_profile", "history");
    }

    OPENMCAD_GUARD("openmcad_create_polygon_profile",
    {
        openmcad::ops::create_polygon_profile(
            openmcad::make_vec2_span(points, points_count),
            openmcad::Transform::from(frame),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}


/* --- construction -------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_extrude(
    uint64_t profile,
    const double* direction,
    double distance,
    int32_t capped,
    uint64_t* result,
    uint64_t* history)
{
    if (direction == nullptr)
    {
        return openmcad::fail_null("openmcad_extrude", "direction");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_extrude", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_extrude", "history");
    }

    OPENMCAD_GUARD("openmcad_extrude",
    {
        openmcad::ops::extrude(
            openmcad::ShapeRef{profile},
            openmcad::Vec3::from(direction),
            distance,
            capped != 0,
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_revolve(
    uint64_t profile,
    const double* axis_point,
    const double* axis_direction,
    double angle,
    int32_t capped,
    uint64_t* result,
    uint64_t* history)
{
    if (axis_point == nullptr)
    {
        return openmcad::fail_null("openmcad_revolve", "axis_point");
    }

    if (axis_direction == nullptr)
    {
        return openmcad::fail_null("openmcad_revolve", "axis_direction");
    }

    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_revolve", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_revolve", "history");
    }

    OPENMCAD_GUARD("openmcad_revolve",
    {
        openmcad::ops::revolve(
            openmcad::ShapeRef{profile},
            openmcad::Vec3::from(axis_point),
            openmcad::Vec3::from(axis_direction),
            angle,
            capped != 0,
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}


/* --- modification -------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_boolean(
    int32_t operation,
    uint64_t target,
    const uint64_t* tools, int32_t tools_count,
    double tolerance,
    double fuzzy_tolerance,
    uint64_t* result,
    uint64_t* history,
    int32_t* rung)
{
    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_boolean", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_boolean", "history");
    }

    if (rung == nullptr)
    {
        return openmcad::fail_null("openmcad_boolean", "rung");
    }

    OPENMCAD_GUARD("openmcad_boolean",
    {
        openmcad::ops::boolean(
            operation,
            openmcad::ShapeRef{target},
            openmcad::make_span(tools, tools_count),
            tolerance,
            fuzzy_tolerance,
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history},
            *rung);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_fillet(
    uint64_t body,
    const uint64_t* edges, int32_t edges_count,
    const double* radii, int32_t radii_count,
    double tolerance,
    uint64_t* result,
    uint64_t* history,
    int32_t* rung)
{
    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_fillet", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_fillet", "history");
    }

    if (rung == nullptr)
    {
        return openmcad::fail_null("openmcad_fillet", "rung");
    }

    OPENMCAD_GUARD("openmcad_fillet",
    {
        openmcad::ops::fillet(
            openmcad::ShapeRef{body},
            openmcad::make_span(edges, edges_count),
            openmcad::make_span(radii, radii_count),
            tolerance,
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history},
            *rung);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_chamfer(
    uint64_t body,
    const uint64_t* edges, int32_t edges_count,
    const double* distances, int32_t distances_count,
    double tolerance,
    uint64_t* result,
    uint64_t* history,
    int32_t* rung)
{
    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_chamfer", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_chamfer", "history");
    }

    if (rung == nullptr)
    {
        return openmcad::fail_null("openmcad_chamfer", "rung");
    }

    OPENMCAD_GUARD("openmcad_chamfer",
    {
        openmcad::ops::chamfer(
            openmcad::ShapeRef{body},
            openmcad::make_span(edges, edges_count),
            openmcad::make_span(distances, distances_count),
            tolerance,
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history},
            *rung);
        return OPENMCAD_OK;
    })
}


/* --- queries ------------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mass_properties(
    uint64_t shape,
    double density,
    double* values, int32_t values_capacity, int32_t* values_required,
    int32_t* accuracy)
{
    if (accuracy == nullptr)
    {
        return openmcad::fail_null("openmcad_mass_properties", "accuracy");
    }

    OPENMCAD_GUARD("openmcad_mass_properties",
    {
        openmcad::ops::mass_properties(
            openmcad::ShapeRef{shape},
            density,
            openmcad::OutBuffer<double>{values, values_capacity, values_required},
            *accuracy);
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mass_properties",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_bounding_box(
    uint64_t shape,
    double* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_bounding_box",
    {
        openmcad::ops::bounding_box(
            openmcad::ShapeRef{shape},
            openmcad::OutBuffer<double>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_bounding_box",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_topology_counts(
    uint64_t shape,
    int32_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_topology_counts",
    {
        openmcad::ops::topology_counts(
            openmcad::ShapeRef{shape},
            openmcad::OutBuffer<int32_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_topology_counts",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_enumerate(
    uint64_t shape,
    int32_t kind,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_enumerate",
    {
        openmcad::ops::enumerate(
            openmcad::ShapeRef{shape},
            kind,
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_enumerate",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_entity_kind(
    uint64_t shape,
    uint64_t entity,
    int32_t* kind)
{
    if (kind == nullptr)
    {
        return openmcad::fail_null("openmcad_entity_kind", "kind");
    }

    OPENMCAD_GUARD("openmcad_entity_kind",
    {
        openmcad::ops::entity_kind(
            openmcad::ShapeRef{shape},
            openmcad::EntityRef{entity},
            *kind);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_check_validity(
    uint64_t shape,
    int32_t* is_valid,
    int32_t* is_closed)
{
    if (is_valid == nullptr)
    {
        return openmcad::fail_null("openmcad_check_validity", "is_valid");
    }

    if (is_closed == nullptr)
    {
        return openmcad::fail_null("openmcad_check_validity", "is_closed");
    }

    OPENMCAD_GUARD("openmcad_check_validity",
    {
        openmcad::ops::check_validity(
            openmcad::ShapeRef{shape},
            *is_valid,
            *is_closed);
        return OPENMCAD_OK;
    })
}


/* --- tessellation -------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_triangulate(
    uint64_t shape,
    double chordal_deviation,
    double angular_deviation,
    int32_t relative,
    int32_t compute_normals,
    uint64_t* mesh)
{
    if (mesh == nullptr)
    {
        return openmcad::fail_null("openmcad_triangulate", "mesh");
    }

    OPENMCAD_GUARD("openmcad_triangulate",
    {
        openmcad::ops::triangulate(
            openmcad::ShapeRef{shape},
            chordal_deviation,
            angular_deviation,
            relative != 0,
            compute_normals != 0,
            openmcad::MeshOut{mesh});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_counts(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_counts",
    {
        openmcad::ops::mesh_counts(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<int32_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_counts",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_positions(
    uint64_t mesh,
    double* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_positions",
    {
        openmcad::ops::mesh_positions(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<double>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_positions",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_normals(
    uint64_t mesh,
    double* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_normals",
    {
        openmcad::ops::mesh_normals(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<double>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_normals",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_indices(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_indices",
    {
        openmcad::ops::mesh_indices(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<int32_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_indices",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_triangle_faces(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_triangle_faces",
    {
        openmcad::ops::mesh_triangle_faces(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<int32_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_triangle_faces",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_faces(
    uint64_t mesh,
    uint64_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_faces",
    {
        openmcad::ops::mesh_faces(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<uint64_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_faces",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_edge_offsets(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_edge_offsets",
    {
        openmcad::ops::mesh_edge_offsets(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<int32_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_edge_offsets",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_edge_positions(
    uint64_t mesh,
    double* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_edge_positions",
    {
        openmcad::ops::mesh_edge_positions(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<double>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_edge_positions",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_edge_tags(
    uint64_t mesh,
    uint64_t* values, int32_t values_capacity, int32_t* values_required)
{
    OPENMCAD_GUARD("openmcad_mesh_edge_tags",
    {
        openmcad::ops::mesh_edge_tags(
            openmcad::MeshRef{mesh},
            openmcad::OutBuffer<uint64_t>{values, values_capacity, values_required});
        if (!openmcad::buffer_satisfied(values, values_capacity, values_required))
        {
            openmcad::record_error("openmcad_mesh_edge_tags",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}


/* --- serialisation ------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_write_brep(
    uint64_t shape,
    uint8_t* data, int32_t data_capacity, int32_t* data_required)
{
    OPENMCAD_GUARD("openmcad_write_brep",
    {
        openmcad::ops::write_brep(
            openmcad::ShapeRef{shape},
            openmcad::OutBuffer<uint8_t>{data, data_capacity, data_required});
        if (!openmcad::buffer_satisfied(data, data_capacity, data_required))
        {
            openmcad::record_error("openmcad_write_brep",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_read_brep(
    const uint8_t* data, int32_t data_count,
    uint64_t* result,
    uint64_t* history)
{
    if (result == nullptr)
    {
        return openmcad::fail_null("openmcad_read_brep", "result");
    }

    if (history == nullptr)
    {
        return openmcad::fail_null("openmcad_read_brep", "history");
    }

    OPENMCAD_GUARD("openmcad_read_brep",
    {
        openmcad::ops::read_brep(
            openmcad::make_span(data, data_count),
            openmcad::ShapeOut{result},
            openmcad::HistoryOut{history});
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_write_step(
    const uint64_t* shapes, int32_t shapes_count,
    const char* path,
    int32_t* bytes_written)
{
    if (path == nullptr)
    {
        return openmcad::fail_null("openmcad_write_step", "path");
    }

    if (bytes_written == nullptr)
    {
        return openmcad::fail_null("openmcad_write_step", "bytes_written");
    }

    OPENMCAD_GUARD("openmcad_write_step",
    {
        openmcad::ops::write_step(
            openmcad::make_span(shapes, shapes_count),
            path,
            *bytes_written);
        return OPENMCAD_OK;
    })
}


/* --- history ------------------------------------------------------------------- */

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_generated(
    uint64_t history,
    uint64_t input,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_history_generated",
    {
        openmcad::ops::history_generated(
            openmcad::HistoryRef{history},
            openmcad::EntityRef{input},
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_history_generated",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_modified(
    uint64_t history,
    uint64_t input,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_history_modified",
    {
        openmcad::ops::history_modified(
            openmcad::HistoryRef{history},
            openmcad::EntityRef{input},
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_history_modified",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_is_deleted(
    uint64_t history,
    uint64_t input,
    int32_t* deleted)
{
    if (deleted == nullptr)
    {
        return openmcad::fail_null("openmcad_history_is_deleted", "deleted");
    }

    OPENMCAD_GUARD("openmcad_history_is_deleted",
    {
        openmcad::ops::history_is_deleted(
            openmcad::HistoryRef{history},
            openmcad::EntityRef{input},
            *deleted);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_new_entities(
    uint64_t history,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_history_new_entities",
    {
        openmcad::ops::history_new_entities(
            openmcad::HistoryRef{history},
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_history_new_entities",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_role_of(
    uint64_t history,
    uint64_t output,
    int32_t* role)
{
    if (role == nullptr)
    {
        return openmcad::fail_null("openmcad_history_role_of", "role");
    }

    OPENMCAD_GUARD("openmcad_history_role_of",
    {
        openmcad::ops::history_role_of(
            openmcad::HistoryRef{history},
            openmcad::EntityRef{output},
            *role);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_source_of(
    uint64_t history,
    uint64_t output,
    uint64_t* source)
{
    if (source == nullptr)
    {
        return openmcad::fail_null("openmcad_history_source_of", "source");
    }

    OPENMCAD_GUARD("openmcad_history_source_of",
    {
        openmcad::ops::history_source_of(
            openmcad::HistoryRef{history},
            openmcad::EntityRef{output},
            *source);
        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_outputs(
    uint64_t history,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_history_outputs",
    {
        openmcad::ops::history_outputs(
            openmcad::HistoryRef{history},
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_history_outputs",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}

OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_inputs(
    uint64_t history,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required)
{
    OPENMCAD_GUARD("openmcad_history_inputs",
    {
        openmcad::ops::history_inputs(
            openmcad::HistoryRef{history},
            openmcad::OutBuffer<uint64_t>{entities, entities_capacity, entities_required});
        if (!openmcad::buffer_satisfied(entities, entities_capacity, entities_required))
        {
            openmcad::record_error("openmcad_history_inputs",
                "The buffer is too small. Call again with the reported size.");
            return OPENMCAD_ERROR_BUFFER_TOO_SMALL;
        }

        return OPENMCAD_OK;
    })
}
