// <auto-generated>
//     Generated by native/tools/idlgen from native/kernel.api.json.
//     DO NOT EDIT. Change the IDL and re-run `./build.ps1 -Generate`.
//     CI fails if these files are out of step with the IDL.
// </auto-generated>

#include "openmcad_ops.g.h"
#include "openmcad_types.h"

/*
 * Fallback bodies, compiled only when OPENMCAD_WITH_OCCT is off.
 *
 * With these the shim links and exports its whole ABI before a single geometric
 * operation exists. That is worth more than it sounds: the boundary, the handle table,
 * the firewall, the two-call protocol and the C# bindings can all be exercised against a
 * real DLL while the kernel work is still ahead, instead of everything arriving at once.
 *
 * Each throws not_implemented, which the firewall turns into
 * OPENMCAD_ERROR_NOT_IMPLEMENTED with the operation named in the diagnostic.
 */

namespace openmcad::ops {

/* initialize: hand-written in every build; no stub. */

/* shutdown: hand-written in every build; no stub. */

/* version: hand-written in every build; no stub. */

void shape_release(
    openmcad::ShapeRef)
{
    throw openmcad::not_implemented("shape_release");
}

void shape_add_ref(
    openmcad::ShapeRef)
{
    throw openmcad::not_implemented("shape_add_ref");
}

void history_release(
    openmcad::HistoryRef)
{
    throw openmcad::not_implemented("history_release");
}

void mesh_release(
    openmcad::MeshRef)
{
    throw openmcad::not_implemented("mesh_release");
}

/* last_error: hand-written in every build; no stub. */

/* diagnostic_count: hand-written in every build; no stub. */

/* diagnostic_severity: hand-written in every build; no stub. */

/* diagnostic_code: hand-written in every build; no stub. */

/* diagnostic_message: hand-written in every build; no stub. */

/* diagnostic_entities: hand-written in every build; no stub. */

/* diagnostics_clear: hand-written in every build; no stub. */

void create_box(
    double,
    double,
    double,
    const openmcad::Transform&,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("create_box");
}

void create_cylinder(
    double,
    double,
    const openmcad::Transform&,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("create_cylinder");
}

void create_sphere(
    double,
    const openmcad::Transform&,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("create_sphere");
}

void create_cone(
    double,
    double,
    double,
    const openmcad::Transform&,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("create_cone");
}

void create_torus(
    double,
    double,
    const openmcad::Transform&,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("create_torus");
}

void create_polygon_profile(
    std::span<const openmcad::Vec2>,
    const openmcad::Transform&,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("create_polygon_profile");
}

void extrude(
    openmcad::ShapeRef,
    const openmcad::Vec3&,
    double,
    bool,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("extrude");
}

void revolve(
    openmcad::ShapeRef,
    const openmcad::Vec3&,
    const openmcad::Vec3&,
    double,
    bool,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("revolve");
}

void boolean(
    int32_t,
    openmcad::ShapeRef,
    std::span<const uint64_t>,
    double,
    double,
    openmcad::ShapeOut,
    openmcad::HistoryOut,
    int32_t&)
{
    throw openmcad::not_implemented("boolean");
}

void fillet(
    openmcad::ShapeRef,
    std::span<const uint64_t>,
    std::span<const double>,
    double,
    openmcad::ShapeOut,
    openmcad::HistoryOut,
    int32_t&)
{
    throw openmcad::not_implemented("fillet");
}

void chamfer(
    openmcad::ShapeRef,
    std::span<const uint64_t>,
    std::span<const double>,
    double,
    openmcad::ShapeOut,
    openmcad::HistoryOut,
    int32_t&)
{
    throw openmcad::not_implemented("chamfer");
}

void mass_properties(
    openmcad::ShapeRef,
    double,
    openmcad::OutBuffer<double>,
    int32_t&)
{
    throw openmcad::not_implemented("mass_properties");
}

void bounding_box(
    openmcad::ShapeRef,
    openmcad::OutBuffer<double>)
{
    throw openmcad::not_implemented("bounding_box");
}

void topology_counts(
    openmcad::ShapeRef,
    openmcad::OutBuffer<int32_t>)
{
    throw openmcad::not_implemented("topology_counts");
}

void enumerate(
    openmcad::ShapeRef,
    int32_t,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("enumerate");
}

void entity_kind(
    openmcad::ShapeRef,
    openmcad::EntityRef,
    int32_t&)
{
    throw openmcad::not_implemented("entity_kind");
}

void check_validity(
    openmcad::ShapeRef,
    int32_t&,
    int32_t&)
{
    throw openmcad::not_implemented("check_validity");
}

void triangulate(
    openmcad::ShapeRef,
    double,
    double,
    bool,
    bool,
    openmcad::MeshOut)
{
    throw openmcad::not_implemented("triangulate");
}

void mesh_counts(
    openmcad::MeshRef,
    openmcad::OutBuffer<int32_t>)
{
    throw openmcad::not_implemented("mesh_counts");
}

void mesh_positions(
    openmcad::MeshRef,
    openmcad::OutBuffer<double>)
{
    throw openmcad::not_implemented("mesh_positions");
}

void mesh_normals(
    openmcad::MeshRef,
    openmcad::OutBuffer<double>)
{
    throw openmcad::not_implemented("mesh_normals");
}

void mesh_indices(
    openmcad::MeshRef,
    openmcad::OutBuffer<int32_t>)
{
    throw openmcad::not_implemented("mesh_indices");
}

void mesh_triangle_faces(
    openmcad::MeshRef,
    openmcad::OutBuffer<int32_t>)
{
    throw openmcad::not_implemented("mesh_triangle_faces");
}

void mesh_faces(
    openmcad::MeshRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("mesh_faces");
}

void mesh_edge_offsets(
    openmcad::MeshRef,
    openmcad::OutBuffer<int32_t>)
{
    throw openmcad::not_implemented("mesh_edge_offsets");
}

void mesh_edge_positions(
    openmcad::MeshRef,
    openmcad::OutBuffer<double>)
{
    throw openmcad::not_implemented("mesh_edge_positions");
}

void mesh_edge_tags(
    openmcad::MeshRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("mesh_edge_tags");
}

void write_brep(
    openmcad::ShapeRef,
    openmcad::OutBuffer<uint8_t>)
{
    throw openmcad::not_implemented("write_brep");
}

void read_brep(
    std::span<const uint8_t>,
    openmcad::ShapeOut,
    openmcad::HistoryOut)
{
    throw openmcad::not_implemented("read_brep");
}

void write_step(
    std::span<const uint64_t>,
    const char*,
    int32_t&)
{
    throw openmcad::not_implemented("write_step");
}

void history_generated(
    openmcad::HistoryRef,
    openmcad::EntityRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("history_generated");
}

void history_modified(
    openmcad::HistoryRef,
    openmcad::EntityRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("history_modified");
}

void history_is_deleted(
    openmcad::HistoryRef,
    openmcad::EntityRef,
    int32_t&)
{
    throw openmcad::not_implemented("history_is_deleted");
}

void history_new_entities(
    openmcad::HistoryRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("history_new_entities");
}

void history_role_of(
    openmcad::HistoryRef,
    openmcad::EntityRef,
    int32_t&)
{
    throw openmcad::not_implemented("history_role_of");
}

void history_source_of(
    openmcad::HistoryRef,
    openmcad::EntityRef,
    uint64_t&)
{
    throw openmcad::not_implemented("history_source_of");
}

void history_outputs(
    openmcad::HistoryRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("history_outputs");
}

void history_inputs(
    openmcad::HistoryRef,
    openmcad::OutBuffer<uint64_t>)
{
    throw openmcad::not_implemented("history_inputs");
}

} // namespace openmcad::ops
