using System.Collections.Immutable;

using FluentAssertions;

using OpenMCAD.Core.Documents;
using OpenMCAD.Core.Naming;
using OpenMCAD.Math;

using Xunit;

namespace OpenMCAD.Core.Tests;

/// <summary>
/// Persistent names (P3-T08): their structure, their round trip, and how they read.
/// </summary>
/// <remarks>
/// Nothing here resolves anything — that is P3-T09 through P3-T11. What these check is that a name
/// can be compared, stored and read back without becoming a different name, because every one of
/// those is a way for a reference to silently start pointing somewhere else.
/// </remarks>
public sealed class PersistentNameTests
{
    [Fact]
    public void TwoNamesBuiltTheSameWayAreEqual()
    {
        // The trap this guards. A record's generated equality compares an ImmutableArray by its
        // underlying array reference, not element by element, so two names built identically from
        // separate arrays would be unequal. That would not fail loudly during resolution — names
        // would simply never match, and every reference would fall through to the geometric tier.
        FeatureId extrude = FeatureId.New();

        PersistentName first = PersistentName.Of(
            NameSegment.Of(extrude, ProvenanceKind.Generated, EntityRole.SideWall));

        PersistentName second = PersistentName.Of(
            NameSegment.Of(extrude, ProvenanceKind.Generated, EntityRole.SideWall));

        first.Should().Be(second);
        first.GetHashCode().Should().Be(second.GetHashCode());
        (first == second).Should().BeTrue();
    }

    [Fact]
    public void NamesThatDifferAnywhereAreNotEqual()
    {
        FeatureId feature = FeatureId.New();

        PersistentName baseline = PersistentName.Of(
            NameSegment.Of(feature, ProvenanceKind.Generated, EntityRole.SideWall));

        PersistentName differentRole = PersistentName.Of(
            NameSegment.Of(feature, ProvenanceKind.Generated, EntityRole.EndCap));

        PersistentName differentOrdinal = PersistentName.Of(
            NameSegment.Of(feature, ProvenanceKind.Generated, EntityRole.SideWall, ordinal: 1));

        PersistentName differentProvenance = PersistentName.Of(
            NameSegment.Of(feature, ProvenanceKind.Modified, EntityRole.SideWall));

        PersistentName differentFeature = PersistentName.Of(
            NameSegment.Of(FeatureId.New(), ProvenanceKind.Generated, EntityRole.SideWall));

        baseline.Should().NotBe(differentRole);
        baseline.Should().NotBe(differentOrdinal);
        baseline.Should().NotBe(differentProvenance);
        baseline.Should().NotBe(differentFeature);
    }

    [Fact]
    public void SourcesAreComparedByValueAndInOrder()
    {
        FeatureId feature = FeatureId.New();
        FeatureId sketch = FeatureId.New();

        NameSource first = new NameSource.Sketch(sketch, "L3");
        NameSource second = new NameSource.Sketch(sketch, "L4");

        PersistentName forward = Blend(feature, [first, second]);
        PersistentName same = Blend(feature, [new NameSource.Sketch(sketch, "L3"), second]);
        PersistentName reversed = Blend(feature, [second, first]);

        forward.Should().Be(same);

        // The blend between the wall from L3 and the wall from L4 is one edge; naming it the other
        // way round has to be the same edge, but only if the ordering means something consistent.
        // It does mean something -- the sources are declared in a fixed order -- so these differ.
        forward.Should().NotBe(reversed);
    }

    [Fact]
    public void ANameNeedsAtLeastOneSegment()
    {
        Action empty = () => _ = new PersistentName([]);

        empty.Should().Throw<ArgumentException>(
            "a name with no segments describes no entity and could only resolve to nothing");
    }

    [Fact]
    public void TheWorkedExampleFromTheSpecificationReadsAsTheSpecificationShowsIt()
    {
        // §5.3's example: the outer cylindrical face of a fillet applied to the edge between the
        // side wall generated by sketch line L3 of Extrude1 and its end cap.
        FeatureId sketch1 = FeatureId.New();
        FeatureId extrude1 = FeatureId.New();
        FeatureId fillet2 = FeatureId.New();

        PersistentName sideWall = PersistentName.Of(new NameSegment(
            extrude1,
            ProvenanceKind.Generated,
            [new NameSource.Sketch(sketch1, "L3")],
            EntityRole.SideWall));

        PersistentName endCap = PersistentName.Of(
            NameSegment.Of(extrude1, ProvenanceKind.Generated, EntityRole.EndCap));

        PersistentName blend = PersistentName.Of(new NameSegment(
            fillet2,
            ProvenanceKind.Intersection,
            [new NameSource.Entity(sideWall), new NameSource.Entity(endCap)],
            EntityRole.BlendFace));

        string described = blend.Describe(id =>
            id == sketch1 ? "Sketch1" : id == extrude1 ? "Extrude1" : id == fillet2 ? "Fillet2" : null);

        described.Should().Be(
            "Fillet2/BlendFace/from(Extrude1/SideWall/from(Sketch1.L3) & Extrude1/EndCap)");
    }

    [Fact]
    public void AnUnknownFeatureRendersAsItsIdRatherThanFailing()
    {
        // Diagnostics get rendered in places that have no document to hand -- a log line, a crash
        // report, a test failure. Rendering has to degrade rather than throw.
        PersistentName name = PersistentName.Of(
            NameSegment.Of(FeatureId.New(), ProvenanceKind.New, EntityRole.BlendFace));

        name.Describe(_ => null).Should().Contain("feature(").And.Contain("BlendFace");
        name.ToString().Should().Contain("BlendFace");
    }

    [Fact]
    public void AnOrdinalIsShownOnlyWhenItMeansSomething()
    {
        FeatureId feature = FeatureId.New();

        PersistentName only = PersistentName.Of(
            NameSegment.Of(feature, ProvenanceKind.Generated, EntityRole.SideWall));

        PersistentName second = PersistentName.Of(
            NameSegment.Of(feature, ProvenanceKind.Generated, EntityRole.SideWall, ordinal: 2));

        only.Describe(_ => "F").Should().Be("F/SideWall");
        second.Describe(_ => "F").Should().Be("F/SideWall#2");
    }

    [Fact]
    public void EveryFeatureAReferenceDependsOnIsReported()
    {
        // What the rebuild needs in order to know a reference has gone stale: a name mentioning a
        // deleted feature cannot resolve, and the feature holding it is the one to tell the user
        // about. Nested sources count, or a reference could depend on a feature nobody noticed.
        FeatureId sketch = FeatureId.New();
        FeatureId extrude = FeatureId.New();
        FeatureId fillet = FeatureId.New();

        PersistentName wall = PersistentName.Of(new NameSegment(
            extrude,
            ProvenanceKind.Generated,
            [new NameSource.Sketch(sketch, "L1")],
            EntityRole.SideWall));

        PersistentName blend = PersistentName.Of(new NameSegment(
            fillet,
            ProvenanceKind.Intersection,
            [new NameSource.Entity(wall)],
            EntityRole.BlendFace));

        blend.ReferencedFeatures().Should().BeEquivalentTo([sketch, extrude, fillet]);
    }

    [Fact]
    public void ANameSurvivesBeingWrittenDownAndReadBack()
    {
        PersistentName original = Complicated();

        string text = PersistentNameFormat.Write(original);
        PersistentName read = PersistentNameFormat.Read(text);

        read.Should().Be(original);

        // And writing it again gives the same text, so the form is canonical rather than merely
        // reversible -- which is what lets it be a key, or an expected value in a fixture.
        PersistentNameFormat.Write(read).Should().Be(text);
    }

    [Theory]
    [InlineData("SideWall")]
    [InlineData("")]
    [InlineData("a role with spaces")]
    [InlineData("semi;colon:and:colons")]
    [InlineData("Fläche/面/🙂")]
    [InlineData("12:34")]
    public void ARoleCanContainAnythingAtAll(string role)
    {
        // Why the format is length-prefixed rather than delimited. A role is whatever a plugin
        // invents, so any character used as a delimiter is a character that eventually appears in
        // a role -- and an escaping scheme is one more thing that has to agree with itself.
        PersistentName name = PersistentName.Of(
            NameSegment.Of(FeatureId.New(), ProvenanceKind.Generated, new EntityRole(role)));

        PersistentNameFormat.Read(PersistentNameFormat.Write(name)).Should().Be(name);
    }

    [Fact]
    public void ASketchEntityIdCanContainAnythingToo()
    {
        PersistentName name = PersistentName.Of(new NameSegment(
            FeatureId.New(),
            ProvenanceKind.Generated,
            [new NameSource.Sketch(FeatureId.New(), "L3;4:5(weird)")],
            EntityRole.SideWall));

        PersistentNameFormat.Read(PersistentNameFormat.Write(name)).Should().Be(name);
    }

    [Fact]
    public void AGeometricHintSurvivesTheRoundTripExactly()
    {
        // The centroid has to come back bit for bit. A hint read back slightly different would
        // score slightly differently, and tier two accepts a match only by a margin over the
        // runner-up -- so a rounding error is a resolution that flips between runs.
        GeoHint hint = new(
            GeometryKind.Cylinder,
            0.001234567890123,
            new Vec3d(1.0 / 3.0, -2.5e-9, 1e12),
            new Vec3d(0, 0, -1),
            AdjacencyDegree: 4);

        PersistentName name = PersistentName.Of(new NameSegment(
            FeatureId.New(), ProvenanceKind.Generated, [], EntityRole.BlendFace, 0, hint));

        PersistentName read = PersistentNameFormat.Read(PersistentNameFormat.Write(name));

        read.Head.Hint.Should().Be(hint);
        read.Head.Hint!.Centroid.X.Should().Be(1.0 / 3.0);
        read.Head.Hint.Measure.Should().Be(0.001234567890123);
    }

    [Fact]
    public void ANameWithNoHintStaysWithoutOne()
    {
        PersistentName name = PersistentName.Of(
            NameSegment.Of(FeatureId.New(), ProvenanceKind.New, EntityRole.BlendFace));

        PersistentNameFormat.Read(PersistentNameFormat.Write(name)).Head.Hint.Should().BeNull();
    }

    [Fact]
    public void AReferenceFromAFutureVersionIsRefusedRatherThanMisread()
    {
        string text = PersistentNameFormat.Write(Complicated()).Replace("v1;", "v2;", StringComparison.Ordinal);

        Action read = () => PersistentNameFormat.Read(text);

        // Reading it as though it were the current form would produce a name that resolves to the
        // wrong entity, which is worse than not opening the file.
        read.Should().Throw<FormatException>().WithMessage("*version 2*");
    }

    [Theory]
    [InlineData("")]
    [InlineData("nonsense")]
    [InlineData("v1;")]
    [InlineData("v1;0:")]
    [InlineData("v1;1:not-a-guid;")]
    [InlineData("v1;99:")]
    public void RubbishIsRefused(string text)
    {
        PersistentNameFormat.TryRead(text, out PersistentName? name).Should().BeFalse();
        name.Should().BeNull();
    }

    [Fact]
    public void TrailingRubbishIsRefused()
    {
        // A reader that stopped as soon as it had enough would accept a truncated or padded
        // reference and produce a name that is not the one that was written.
        string text = PersistentNameFormat.Write(Complicated()) + "extra";

        PersistentNameFormat.TryRead(text, out _).Should().BeFalse();
    }

    [Fact]
    public void ALengthThatRunsPastTheEndIsRefused()
    {
        PersistentNameFormat.TryRead("v1;1:" + Guid.NewGuid().ToString("D") + ";0;99:x", out _)
            .Should().BeFalse();
    }

    [Fact]
    public void AMultiStepNameKeepsItsOrder()
    {
        FeatureId created = FeatureId.New();
        FeatureId modified = FeatureId.New();

        PersistentName name = new(
        [
            NameSegment.Of(created, ProvenanceKind.Generated, EntityRole.SideWall),
            NameSegment.Of(modified, ProvenanceKind.Modified, EntityRole.DraftFace),
        ]);

        name.Origin.Feature.Should().Be(created);
        name.Head.Feature.Should().Be(modified);
        name.Feature.Should().Be(modified, "the feature responsible is the most recent one");

        name.Describe(id => id == created ? "Extrude1" : "Draft1")
            .Should().Be("Extrude1/SideWall -> Draft1/DraftFace");

        PersistentNameFormat.Read(PersistentNameFormat.Write(name)).Should().Be(name);
    }

    private static PersistentName Blend(FeatureId feature, ImmutableArray<NameSource> sources)
        => PersistentName.Of(new NameSegment(
            feature, ProvenanceKind.Intersection, sources, EntityRole.BlendFace));

    /// <summary>A name using every part of the structure at once.</summary>
    private static PersistentName Complicated()
    {
        FeatureId sketch = FeatureId.New();
        FeatureId extrude = FeatureId.New();
        FeatureId fillet = FeatureId.New();

        PersistentName wall = PersistentName.Of(new NameSegment(
            extrude,
            ProvenanceKind.Generated,
            [new NameSource.Sketch(sketch, "L3")],
            EntityRole.SideWall,
            2,
            new GeoHint(GeometryKind.Plane, 0.25, new Vec3d(1, 2, 3), Vec3d.UnitZ, 4)));

        return new PersistentName(
        [
            new NameSegment(
                fillet,
                ProvenanceKind.Intersection,
                [
                    new NameSource.Entity(wall),
                    new NameSource.Sketch(sketch, "L4"),
                ],
                EntityRole.BlendFace,
                1,
                new GeoHint(GeometryKind.Cylinder, 0.5, new Vec3d(-1, 0, 0.5), Vec3d.UnitX, 3)),
            NameSegment.Of(FeatureId.New(), ProvenanceKind.Modified, new EntityRole("Custom")),
        ]);
    }
}
