// <auto-generated>
//     Generated by native/tools/idlgen from native/kernel.api.json.
//     DO NOT EDIT. Change the IDL and re-run `./build.ps1 -Generate`.
//     CI fails if these files are out of step with the IDL.
// </auto-generated>

#ifndef OPENMCAD_OCCT_G_H
#define OPENMCAD_OCCT_G_H

#include <stdint.h>

#include "openmcad_occt.h"

#ifdef __cplusplus
extern "C" {
#endif

/* --- lifetime ------------------------------------------------------------------ */

/*
 * Initialises the shim. Must be called once per process before any other entry point. Installs
 * the OCCT signal handler so a floating-point fault inside the kernel becomes a catchable
 * failure rather than a process death.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_initialize(
    void);

/*
 * Releases process-wide shim resources. Optional; provided so leak detection has a clean
 * baseline.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_shutdown(
    void);

/*
 * Returns the shim and kernel version as UTF-8.
 *
 * @param text The version string.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_version(
    char* text, int32_t text_capacity, int32_t* text_required);

/*
 * Drops one reference to a shape. The shape and all its sub-entities become invalid when the
 * last reference goes.
 *
 * @param shape The shape to release.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_shape_release(
    uint64_t shape);

/*
 * Takes an additional reference to a shape.
 *
 * @param shape The shape to reference.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_shape_add_ref(
    uint64_t shape);

/*
 * Releases a history map.
 *
 * @param history The history map to release.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_release(
    uint64_t history);

/*
 * Releases a tessellation.
 *
 * @param mesh The mesh to release.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_release(
    uint64_t mesh);


/* --- diagnostics --------------------------------------------------------------- */

/*
 * Returns a description of the most recent failure on the calling thread.
 *
 * @param text The description.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_last_error(
    char* text, int32_t text_capacity, int32_t* text_required);

/*
 * Returns how many diagnostics the last operation produced.
 *
 * @param count The number of diagnostics.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_count(
    int32_t* count);

/*
 * Returns one diagnostic severity.
 *
 * @param index The diagnostic index.
 *
 * @param severity 0 information, 1 warning, 2 error.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_severity(
    int32_t index,
    int32_t* severity);

/*
 * Returns one diagnostic stable code.
 *
 * @param index The diagnostic index.
 *
 * @param code The code, such as OMK2003.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_code(
    int32_t index,
    char* code, int32_t code_capacity, int32_t* code_required);

/*
 * Returns one diagnostic user-facing message.
 *
 * @param index The diagnostic index.
 *
 * @param message The message.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_message(
    int32_t index,
    char* message, int32_t message_capacity, int32_t* message_required);

/*
 * Returns the entities one diagnostic refers to.
 *
 * @param index The diagnostic index.
 *
 * @param entities The entity tags.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostic_entities(
    int32_t index,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

/*
 * Discards the diagnostics from the last operation.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_diagnostics_clear(
    void);


/* --- primitives ---------------------------------------------------------------- */

/*
 * Creates a box with its minimum corner at the placement origin.
 *
 * @param size_x Extent along local X, in metres.
 *
 * @param size_y Extent along local Y, in metres.
 *
 * @param size_z Extent along local Z, in metres.
 *
 * @param placement Where the local frame sits.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_box(
    double size_x,
    double size_y,
    double size_z,
    const double* placement,
    uint64_t* result,
    uint64_t* history);

/*
 * Creates a cylinder about the local Z axis.
 *
 * @param radius Radius in metres.
 *
 * @param height Height in metres.
 *
 * @param placement Where the local frame sits.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_cylinder(
    double radius,
    double height,
    const double* placement,
    uint64_t* result,
    uint64_t* history);

/*
 * Creates a sphere centred on the placement origin.
 *
 * @param radius Radius in metres.
 *
 * @param placement Where the local frame sits.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_sphere(
    double radius,
    const double* placement,
    uint64_t* result,
    uint64_t* history);

/*
 * Creates a cone or truncated cone about the local Z axis.
 *
 * @param bottom_radius Radius at the base, in metres.
 *
 * @param top_radius Radius at the top, in metres.
 *
 * @param height Height in metres.
 *
 * @param placement Where the local frame sits.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_cone(
    double bottom_radius,
    double top_radius,
    double height,
    const double* placement,
    uint64_t* result,
    uint64_t* history);

/*
 * Creates a torus about the local Z axis.
 *
 * @param major_radius Distance from the axis to the tube centre.
 *
 * @param minor_radius Tube radius.
 *
 * @param placement Where the local frame sits.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_torus(
    double major_radius,
    double minor_radius,
    const double* placement,
    uint64_t* result,
    uint64_t* history);

/*
 * Creates a closed planar profile from an outline.
 *
 * @param points The outline in the frame XY plane, without a repeated closing point.
 *
 * @param frame Maps the profile plane into the world.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_create_polygon_profile(
    const double* points, int32_t points_count,
    const double* frame,
    uint64_t* result,
    uint64_t* history);


/* --- construction -------------------------------------------------------------- */

/*
 * Sweeps a profile along a straight path.
 *
 * @param profile The profile to sweep.
 *
 * @param direction The sweep direction, unit length.
 *
 * @param distance How far to sweep, in metres.
 *
 * @param capped Whether to cap the ends, producing a solid.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_extrude(
    uint64_t profile,
    const double* direction,
    double distance,
    int32_t capped,
    uint64_t* result,
    uint64_t* history);

/*
 * Sweeps a profile about an axis.
 *
 * @param profile The profile to sweep.
 *
 * @param axis_point A point on the axis.
 *
 * @param axis_direction The axis direction, unit length.
 *
 * @param angle How far to revolve, in radians.
 *
 * @param capped Whether to cap the ends of a partial revolution.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_revolve(
    uint64_t profile,
    const double* axis_point,
    const double* axis_direction,
    double angle,
    int32_t capped,
    uint64_t* result,
    uint64_t* history);


/* --- modification -------------------------------------------------------------- */

/*
 * Combines bodies.
 *
 * Fragile: escalates through the retry ladder (PLAN.md 5.2.4) and reports which
 * rung succeeded.
 *
 * @param operation 0 union, 1 subtract, 2 intersect.
 *
 * @param target The body being modified.
 *
 * @param tools The bodies being combined with it.
 *
 * @param tolerance Model tolerance in metres.
 *
 * @param fuzzy_tolerance Relaxed tolerance for rung 3, or zero for none.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 *
 * @param rung Which rung of the retry ladder produced the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_boolean(
    int32_t operation,
    uint64_t target,
    const uint64_t* tools, int32_t tools_count,
    double tolerance,
    double fuzzy_tolerance,
    uint64_t* result,
    uint64_t* history,
    int32_t* rung);

/*
 * Rounds edges.
 *
 * Fragile: escalates through the retry ladder (PLAN.md 5.2.4) and reports which
 * rung succeeded.
 *
 * @param body The body to modify.
 *
 * @param edges The edges to round.
 *
 * @param radii One radius per edge, in metres.
 *
 * @param tolerance Model tolerance in metres.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 *
 * @param rung Which rung of the retry ladder produced the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_fillet(
    uint64_t body,
    const uint64_t* edges, int32_t edges_count,
    const double* radii, int32_t radii_count,
    double tolerance,
    uint64_t* result,
    uint64_t* history,
    int32_t* rung);

/*
 * Bevels edges.
 *
 * Fragile: escalates through the retry ladder (PLAN.md 5.2.4) and reports which
 * rung succeeded.
 *
 * @param body The body to modify.
 *
 * @param edges The edges to bevel.
 *
 * @param distances One setback distance per edge, in metres.
 *
 * @param tolerance Model tolerance in metres.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 *
 * @param rung Which rung of the retry ladder produced the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_chamfer(
    uint64_t body,
    const uint64_t* edges, int32_t edges_count,
    const double* distances, int32_t distances_count,
    double tolerance,
    uint64_t* result,
    uint64_t* history,
    int32_t* rung);


/* --- queries ------------------------------------------------------------------- */

/*
 * Computes volume, area, centroid, and inertia.
 *
 * @param shape The shape to measure.
 *
 * @param density Density in kilograms per cubic metre.
 *
 * @param values Eleven doubles: volume, area, centroid xyz, then Ixx Iyy Izz Ixy Ixz Iyz.
 *        Always 11 elements; the size query can be skipped.
 *
 * @param accuracy 0 exact, 1 approximate.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mass_properties(
    uint64_t shape,
    double density,
    double* values, int32_t values_capacity, int32_t* values_required,
    int32_t* accuracy);

/*
 * Computes the axis-aligned bound.
 *
 * @param shape The shape to bound.
 *
 * @param values Six doubles: min xyz then max xyz.
 *        Always 6 elements; the size query can be skipped.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_bounding_box(
    uint64_t shape,
    double* values, int32_t values_capacity, int32_t* values_required);

/*
 * Counts topological entities.
 *
 * @param shape The shape to count.
 *
 * @param values Six counts: solids, shells, faces, wires, edges, vertices.
 *        Always 6 elements; the size query can be skipped.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_topology_counts(
    uint64_t shape,
    int32_t* values, int32_t values_capacity, int32_t* values_required);

/*
 * Lists entities of one kind in canonical order.
 *
 * @param shape The shape to enumerate.
 *
 * @param kind The SubEntityKind to list.
 *
 * @param entities The entity tags, in canonical order.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_enumerate(
    uint64_t shape,
    int32_t kind,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

/*
 * Returns what kind of entity a tag refers to.
 *
 * @param shape The owning shape.
 *
 * @param entity The entity tag.
 *
 * @param kind The SubEntityKind.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_entity_kind(
    uint64_t shape,
    uint64_t entity,
    int32_t* kind);

/*
 * Checks a shape for structural validity.
 *
 * @param shape The shape to check.
 *
 * @param is_valid Non-zero when the shape is sound.
 *
 * @param is_closed Non-zero when its shells are closed.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_check_validity(
    uint64_t shape,
    int32_t* is_valid,
    int32_t* is_closed);


/* --- tessellation -------------------------------------------------------------- */

/*
 * Triangulates a shape, returning a mesh handle.
 *
 * @param shape The shape to tessellate.
 *
 * @param chordal_deviation Maximum deviation from the true surface, in metres.
 *
 * @param angular_deviation Maximum angle between adjacent facet normals, in radians.
 *
 * @param relative Whether the chordal deviation is relative to shape size.
 *
 * @param compute_normals Whether to compute per-vertex normals.
 *
 * @param mesh The resulting mesh.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_triangulate(
    uint64_t shape,
    double chordal_deviation,
    double angular_deviation,
    int32_t relative,
    int32_t compute_normals,
    uint64_t* mesh);

/*
 * Returns a mesh size, so buffers can be allocated once.
 *
 * @param mesh The mesh.
 *
 * @param values Three counts: vertices, triangles, faces.
 *        Always 3 elements; the size query can be skipped.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_counts(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns vertex positions as XYZ triples in metres.
 *
 * @param mesh The mesh.
 *
 * @param values Three doubles per vertex.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_positions(
    uint64_t mesh,
    double* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns per-vertex normals as XYZ triples.
 *
 * @param mesh The mesh.
 *
 * @param values Three doubles per vertex, empty if not computed.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_normals(
    uint64_t mesh,
    double* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns triangle vertex indices, three per triangle.
 *
 * @param mesh The mesh.
 *
 * @param values Three indices per triangle.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_indices(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns the face index each triangle came from.
 *
 * @param mesh The mesh.
 *
 * @param values One index per triangle.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_triangle_faces(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns the face tags the triangle attribution indexes into.
 *
 * @param mesh The mesh.
 *
 * @param values The face tags, in order.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_faces(
    uint64_t mesh,
    uint64_t* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns where each edge polyline starts, plus a final total.
 *
 * @param mesh The mesh.
 *
 * @param values One point index per polyline, then the total point count, so polyline i
 *        spans [values[i], values[i+1]). Empty when there are no edges.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_edge_offsets(
    uint64_t mesh,
    int32_t* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns edge polyline points as XYZ triples in metres.
 *
 * @param mesh The mesh.
 *
 * @param values Three doubles per point, concatenated across polylines.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_edge_positions(
    uint64_t mesh,
    double* values, int32_t values_capacity, int32_t* values_required);

/*
 * Returns the edge each polyline represents.
 *
 * @param mesh The mesh.
 *
 * @param values One edge tag per polyline, in the same order as the offsets.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_mesh_edge_tags(
    uint64_t mesh,
    uint64_t* values, int32_t values_capacity, int32_t* values_required);


/* --- serialisation ------------------------------------------------------------- */

/*
 * Writes a shape to the kernel native format.
 *
 * @param shape The shape to write.
 *
 * @param data The bytes.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_write_brep(
    uint64_t shape,
    uint8_t* data, int32_t data_capacity, int32_t* data_required);

/*
 * Reads a shape written by write_brep.
 *
 * @param data The bytes to read.
 *
 * @param result The resulting shape.
 *
 * @param history The correspondence between the inputs and the result.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_read_brep(
    const uint8_t* data, int32_t data_count,
    uint64_t* result,
    uint64_t* history);

/*
 * Writes shapes as a STEP AP242 file.
 *
 * @param shapes The shapes to write.
 *
 * @param path Where to write. The OCCT writer wants a path, not a stream.
 *
 * @param bytes_written How many bytes were written.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_write_step(
    const uint64_t* shapes, int32_t shapes_count,
    const char* path,
    int32_t* bytes_written);


/* --- history ------------------------------------------------------------------- */

/*
 * Returns the entities an input caused to come into existence.
 *
 * @param history The history map.
 *
 * @param input The input entity.
 *
 * @param entities The generated entities, sorted.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_generated(
    uint64_t history,
    uint64_t input,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

/*
 * Returns the altered successors of an input.
 *
 * @param history The history map.
 *
 * @param input The input entity.
 *
 * @param entities The successors, sorted.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_modified(
    uint64_t history,
    uint64_t input,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

/*
 * Returns whether an input has no successor.
 *
 * @param history The history map.
 *
 * @param input The input entity.
 *
 * @param deleted Non-zero when the entity was consumed.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_is_deleted(
    uint64_t history,
    uint64_t input,
    int32_t* deleted);

/*
 * Returns the entities created from nothing.
 *
 * @param history The history map.
 *
 * @param entities The new entities, sorted.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_new_entities(
    uint64_t history,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

/*
 * Returns what an output entity is, in the terms of the operation that made it.
 *
 * @param history The history map.
 *
 * @param output The output entity.
 *
 * @param role The OperationRole. Zero means unassigned, which is a defect.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_role_of(
    uint64_t history,
    uint64_t output,
    int32_t* role);

/*
 * Returns the input an output came from.
 *
 * @param history The history map.
 *
 * @param output The output entity.
 *
 * @param source The source entity tag, or zero for entities created from nothing.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_source_of(
    uint64_t history,
    uint64_t output,
    uint64_t* source);

/*
 * Returns every output the map describes.
 *
 * @param history The history map.
 *
 * @param entities The outputs, sorted.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_outputs(
    uint64_t history,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

/*
 * Returns every input the map describes.
 *
 * @param history The history map.
 *
 * @param entities The inputs, sorted.
 */
OPENMCAD_API OpenMcadStatus OPENMCAD_CALL openmcad_history_inputs(
    uint64_t history,
    uint64_t* entities, int32_t entities_capacity, int32_t* entities_required);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* OPENMCAD_OCCT_G_H */
