// <auto-generated>
//     Generated by native/tools/idlgen from native/kernel.api.json.
//     DO NOT EDIT. Change the IDL and re-run `./build.ps1 -Generate`.
//     CI fails if these files are out of step with the IDL.
// </auto-generated>

#ifndef OPENMCAD_OPS_G_H
#define OPENMCAD_OPS_G_H

#include <span>
#include <stdint.h>

#include "openmcad_types.h"

/*
 * The operation bodies, which are hand-written -- everything around them is generated.
 *
 * By the time one of these is called the dispatch layer has already: rejected null
 * output pointers, resolved handles against the handle table, wrapped raw pointers in
 * spans, and installed the exception firewall. An implementation may therefore throw
 * freely -- Standard_Failure included -- and work in C++ types rather than in ABI types.
 *
 * None of these signatures mentions OCCT. The generator does not know what kernel is
 * underneath, which is what keeps ADR-0002 swap path honest.
 */

namespace openmcad::ops {

/* --- lifetime ------------------------------------------------------------------ */

void initialize(
    );

void shutdown(
    );

void version(
    openmcad::OutBuffer<char> text);

void shape_release(
    openmcad::ShapeRef shape);

void shape_add_ref(
    openmcad::ShapeRef shape);

void history_release(
    openmcad::HistoryRef history);

void mesh_release(
    openmcad::MeshRef mesh);


/* --- diagnostics --------------------------------------------------------------- */

void last_error(
    openmcad::OutBuffer<char> text);

void diagnostic_count(
    int32_t& count);

void diagnostic_severity(
    int32_t index,
    int32_t& severity);

void diagnostic_code(
    int32_t index,
    openmcad::OutBuffer<char> code);

void diagnostic_message(
    int32_t index,
    openmcad::OutBuffer<char> message);

void diagnostic_entities(
    int32_t index,
    openmcad::OutBuffer<uint64_t> entities);

void diagnostics_clear(
    );


/* --- primitives ---------------------------------------------------------------- */

void create_box(
    double size_x,
    double size_y,
    double size_z,
    const openmcad::Transform& placement,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void create_cylinder(
    double radius,
    double height,
    const openmcad::Transform& placement,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void create_sphere(
    double radius,
    const openmcad::Transform& placement,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void create_cone(
    double bottom_radius,
    double top_radius,
    double height,
    const openmcad::Transform& placement,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void create_torus(
    double major_radius,
    double minor_radius,
    const openmcad::Transform& placement,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void create_polygon_profile(
    std::span<const openmcad::Vec2> points,
    const openmcad::Transform& frame,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);


/* --- construction -------------------------------------------------------------- */

void extrude(
    openmcad::ShapeRef profile,
    const openmcad::Vec3& direction,
    double distance,
    bool capped,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void revolve(
    openmcad::ShapeRef profile,
    const openmcad::Vec3& axis_point,
    const openmcad::Vec3& axis_direction,
    double angle,
    bool capped,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);


/* --- modification -------------------------------------------------------------- */

void boolean(
    int32_t operation,
    openmcad::ShapeRef target,
    std::span<const uint64_t> tools,
    double tolerance,
    double fuzzy_tolerance,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history,
    int32_t& rung);

void fillet(
    openmcad::ShapeRef body,
    std::span<const uint64_t> edges,
    std::span<const double> radii,
    double tolerance,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history,
    int32_t& rung);

void chamfer(
    openmcad::ShapeRef body,
    std::span<const uint64_t> edges,
    std::span<const double> distances,
    double tolerance,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history,
    int32_t& rung);


/* --- queries ------------------------------------------------------------------- */

void mass_properties(
    openmcad::ShapeRef shape,
    double density,
    openmcad::OutBuffer<double> values,
    int32_t& accuracy);

void bounding_box(
    openmcad::ShapeRef shape,
    openmcad::OutBuffer<double> values);

void topology_counts(
    openmcad::ShapeRef shape,
    openmcad::OutBuffer<int32_t> values);

void enumerate(
    openmcad::ShapeRef shape,
    int32_t kind,
    openmcad::OutBuffer<uint64_t> entities);

void entity_kind(
    openmcad::ShapeRef shape,
    openmcad::EntityRef entity,
    int32_t& kind);

void check_validity(
    openmcad::ShapeRef shape,
    int32_t& is_valid,
    int32_t& is_closed);


/* --- tessellation -------------------------------------------------------------- */

void triangulate(
    openmcad::ShapeRef shape,
    double chordal_deviation,
    double angular_deviation,
    bool relative,
    bool compute_normals,
    openmcad::MeshOut mesh);

void mesh_counts(
    openmcad::MeshRef mesh,
    openmcad::OutBuffer<int32_t> values);

void mesh_positions(
    openmcad::MeshRef mesh,
    openmcad::OutBuffer<double> values);

void mesh_normals(
    openmcad::MeshRef mesh,
    openmcad::OutBuffer<double> values);

void mesh_indices(
    openmcad::MeshRef mesh,
    openmcad::OutBuffer<int32_t> values);

void mesh_triangle_faces(
    openmcad::MeshRef mesh,
    openmcad::OutBuffer<int32_t> values);

void mesh_faces(
    openmcad::MeshRef mesh,
    openmcad::OutBuffer<uint64_t> values);


/* --- serialisation ------------------------------------------------------------- */

void write_brep(
    openmcad::ShapeRef shape,
    openmcad::OutBuffer<uint8_t> data);

void read_brep(
    std::span<const uint8_t> data,
    openmcad::ShapeOut result,
    openmcad::HistoryOut history);

void write_step(
    std::span<const uint64_t> shapes,
    const char* path,
    int32_t& bytes_written);


/* --- history ------------------------------------------------------------------- */

void history_generated(
    openmcad::HistoryRef history,
    openmcad::EntityRef input,
    openmcad::OutBuffer<uint64_t> entities);

void history_modified(
    openmcad::HistoryRef history,
    openmcad::EntityRef input,
    openmcad::OutBuffer<uint64_t> entities);

void history_is_deleted(
    openmcad::HistoryRef history,
    openmcad::EntityRef input,
    int32_t& deleted);

void history_new_entities(
    openmcad::HistoryRef history,
    openmcad::OutBuffer<uint64_t> entities);

void history_role_of(
    openmcad::HistoryRef history,
    openmcad::EntityRef output,
    int32_t& role);

void history_source_of(
    openmcad::HistoryRef history,
    openmcad::EntityRef output,
    uint64_t& source);

void history_outputs(
    openmcad::HistoryRef history,
    openmcad::OutBuffer<uint64_t> entities);

void history_inputs(
    openmcad::HistoryRef history,
    openmcad::OutBuffer<uint64_t> entities);

} // namespace openmcad::ops

#endif /* OPENMCAD_OPS_G_H */
